# Use the official MySQL image from Docker Hub
FROM mysql:8.0

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=toor
ENV MYSQL_DATABASE=talkerbook_db
ENV MYSQL_USER=talkerbook_admin
ENV MYSQL_PASSWORD=YourStrong!Passw0rd

# Expose the MySQL port
EXPOSE 3306
